# Generated by Django 3.2.7 on 2021-09-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destiny', models.CharField(max_length=100)),
            ],
        ),
    ]
